apiVersion: v1
kind: Pod
metadata:
  name: python-flask-pod
spec:
  containers:
  - name: python-flask
    image: python:3.8
    command: ["sh", "-c", "pip install flask && python -c \"from flask import Flask; app = Flask(__name__); @app.route('/') def hello(): return 'Hello World!'; app.run(host='0.0.0.0', port=5000)\""]
    ports:
    - containerPort: 5000