apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loadbalancer-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes Services Test - LoadBalancer</title>
    </head>
    <body>
        <h1>LoadBalancer Service</h1>
        <p>This service type is accessible from outside the cluster via a cloud provider's load balancer.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-loadbalancer
  template:
    metadata:
      labels:
        app: nginx-loadbalancer
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-loadbalancer-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-loadbalancer-config
        configMap:
          name: nginx-loadbalancer-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx-loadbalancer
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer