apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-nodeport-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes Services Test - NodePort</title>
    </head>
    <body>
        <h1>NodePort Service</h1>
        <p>This service type is accessible from outside the cluster via Node's IP and NodePort.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-nodeport-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-nodeport-config
        configMap:
          name: nginx-nodeport-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx-nodeport
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
  type: NodePort
