apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    type: web
  name: mypod-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: web
  type: NodePort
status:
  loadBalancer: {}
