apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: web
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: mypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
